# Generated by Django 4.2.4 on 2023-09-25 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('body', models.JSONField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('translation_parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_objects', to='articles.translations')),
            ],
            options={
                'unique_together': {('language', 'title')},
            },
        ),
    ]
